# Generated by Django 2.2.11 on 2020-05-21 19:19

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq_desc', models.TextField(verbose_name='Descrição:')),
                ('arq_nome', models.CharField(max_length=100, null=True, verbose_name='Nome:')),
                ('arq_imagem', stdimage.models.StdImageField(null=True, upload_to='imagem_projeto_arq', verbose_name='Imagem:')),
                ('arq_localizacao_documento', models.FileField(max_length=1000, null=True, upload_to='arquivos_projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_titulo', models.CharField(max_length=100, verbose_name='Título do projeto:')),
                ('pro_imagem', stdimage.models.StdImageField(null=True, upload_to='imagem_projeto', verbose_name='Imagem:')),
                ('pro_desc', models.TextField(verbose_name='Descrição:')),
                ('pro_financiamento', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Financiamento:')),
                ('pro_financiadora', models.CharField(max_length=100, verbose_name='Instituição financiadora:')),
                ('pro_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação:')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosDosUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdu_projetos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projetos')),
            ],
        ),
    ]
