# Generated by Django 2.2.4 on 2020-09-14 15:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import projetos.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq_colecao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colecao:')),
                ('arq_nivel_de_acesso', models.CharField(choices=[('PU', 'Publico'), ('PR', 'Privado')], max_length=2, null=True, verbose_name='Nivel de acesso:')),
                ('arq_assunto', models.CharField(max_length=100, null=True, verbose_name='Assunto:')),
                ('arq_cargo_des', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo de Destinatario:')),
                ('arq_cargo_emi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo de Emitente:')),
                ('arq_local_emissao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Local Emissao:')),
                ('arq_custodia', models.CharField(max_length=100, null=True, verbose_name='Instituição de Custodia:')),
                ('arq_idioma', models.CharField(max_length=100, null=True, verbose_name='Idioma:')),
                ('arq_cdd', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Numero de CDD:')),
                ('arq_destinatario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destinatario:')),
                ('arq_emitente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Emitente:')),
                ('arq_estado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado')),
                ('arq_cidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cidade')),
                ('arq_data', models.CharField(blank=True, max_length=10, null=True, verbose_name='Data')),
                ('arq_data_de_registro', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação:')),
                ('arq_nome', models.CharField(max_length=100, null=True, verbose_name='Titulo:')),
                ('arq_localizacao_do_acervo', models.CharField(max_length=100, null=True, verbose_name='Localização do acervo:')),
                ('arq_autenticacao', models.CharField(choices=[('O', 'Original'), ('C', 'Copia')], max_length=1, null=True, verbose_name='Autenticação:')),
                ('arq_tipo_de_formato', models.CharField(max_length=10, null=True, verbose_name='Tipo de Formato:')),
                ('arq_texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aud_duracao', models.DurationField(blank=True, null=True, verbose_name='Duração:')),
                ('aud_audio', models.FileField(blank=True, null=True, upload_to=projetos.models.user_directory_path_audio_file, verbose_name='Audio')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_documento', models.FileField(blank=True, null=True, upload_to=projetos.models.user_directory_path_documento_file, verbose_name='Documento')),
                ('doc_numero_de_paginas', models.DecimalField(blank=True, decimal_places=0, max_digits=3000, null=True, verbose_name='Numero de Paginas:')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fot_tamanho', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamanho:')),
                ('fot_imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='imagem_projeto_arq', verbose_name='Imagem:')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PalavrasChave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_palavras_chaves', models.CharField(max_length=200, null=True, verbose_name='Palavras chaves:')),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioCultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_oficio', models.TextField(blank=True, max_length=100, null=True, verbose_name='Oficio:')),
                ('pc_expressao', models.TextField(blank=True, max_length=100, null=True, verbose_name='Formas de expressão:')),
                ('pc_lugares', models.TextField(blank=True, max_length=100, null=True, verbose_name='Lugares:')),
                ('pc_celebracoes', models.TextField(blank=True, max_length=100, null=True, verbose_name='Celebrações')),
                ('pc_edificacoes', models.TextField(blank=True, max_length=100, null=True, verbose_name='Edificações')),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_titulo', models.CharField(max_length=100, verbose_name='Título do projeto:')),
                ('pro_imagem', stdimage.models.StdImageField(null=True, upload_to='imagem_projeto', verbose_name='Imagem:')),
                ('pro_desc', models.TextField(verbose_name='Descrição:')),
                ('pro_financiamento', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, verbose_name='Financiamento:')),
                ('pro_financiadora', models.CharField(max_length=100, verbose_name='Instituição financiadora:')),
                ('pro_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação:')),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdd_geral', models.CharField(max_length=100, null=True, verbose_name='Tipo de Documento Geral:')),
                ('tdd_especifico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Documento Especifico:')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_video', models.FileField(blank=True, null=True, upload_to=projetos.models.user_directory_path_video_file, verbose_name='Video:')),
                ('vid_duracao', models.DurationField(blank=True, null=True, verbose_name='Duração:')),
                ('vid_arq', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetosDosUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdu_projetos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projetos')),
            ],
        ),
    ]
