# Generated by Django 2.2.11 on 2020-05-21 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetosdosusuarios',
            name='pdu_usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projetos',
            name='pro_inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Instituicao'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='pro_usuarios',
            field=models.ManyToManyField(through='projetos.ProjetosDosUsuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_pro_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Projetos'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_usu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
