# Generated by Django 3.0.6 on 2020-06-06 02:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20200521_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arq_localizacao_documento',
            field=ckeditor.fields.RichTextField(max_length=1000, null=True),
        ),
    ]
