# Generated by Django 2.2.4 on 2020-09-14 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20200914_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arq_tdd_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipodedocumento', to='projetos.TiposDeDocumento'),
        ),
    ]
