# Generated by Django 3.0.6 on 2020-06-06 02:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20200605_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arq_localizacao_documento',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, null=True),
        ),
    ]
