# Generated by Django 2.2.4 on 2020-09-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20200914_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='aud_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='patrimoniocultura',
            name='pc_arq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrimoniocultura', to='projetos.Arquivo'),
        ),
    ]
