# Generated by Django 3.0.6 on 2020-07-05 00:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20200605_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='arq_imagem',
        ),
        migrations.RemoveField(
            model_name='arquivo',
            name='arq_localizacao_documento',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_assunto',
            field=models.CharField(max_length=100, null=True, verbose_name='Assunto:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_cidade',
            field=models.CharField(max_length=5, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_colecao',
            field=models.CharField(max_length=100, null=True, verbose_name='Colecao:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_data',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_data_de_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de publicação:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_estado',
            field=models.CharField(max_length=5, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_nivel_de_acesso',
            field=models.CharField(choices=[('PU', 'Publico'), ('PR', 'Privado')], max_length=2, null=True, verbose_name='Nivel de acesso:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_palavras_chaves',
            field=models.CharField(max_length=200, null=True, verbose_name='Palavras chaves:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_tipo_de_documento',
            field=models.CharField(choices=[('Documentos Pessoais', (('ID', 'Identidade'), ('CN', 'Certidão de nascimento'), ('CB', 'Certidão de batismo'), ('CC', 'Certidão de casamento'), ('CO', 'Certidão de óbito'))), ('Pessoais', (('CO', 'Correspondência'), ('DI', 'Diário'), ('AN', 'Anotação'), ('RC', 'Receita de comida'), ('DM', 'Documento médico'))), ('Jurídicos', (('vhs', 'Processo'), ('dvd', 'Testamento'), ('dvd', 'Inventário'), ('dvd', 'Depoimento'), ('dvd', 'Despacho'), ('dvd', 'Sentença'), ('dvd', 'Acórdão'))), ('Governamentais', (('vhs', 'Relatório'), ('dvd', 'Ata'), ('dvd', 'Lei'), ('dvd', 'Resolução'), ('dvd', 'Decreto'), ('dvd', 'Constituição'), ('dvd', 'Listas'), ('dvd', 'Registro de imóvel'), ('dvd', 'Registro de cobrança'), ('dvd', 'Registro de trabalho'), ('dvd', 'Carta de alforria'), ('dvd', 'Recibo de compra e venda'), ('dvd', 'Apólice'))), ('Relatos', (('vhs', 'Depoimento'), ('dvd', 'Entrevista'), ('dvd', 'Relato'), ('dvd', 'Música'))), ('Iconográficos', (('vhs', 'Fotografia'), ('dvd', 'Desenho'), ('dvd', 'Mapa'), ('dvd', 'Pintura'), ('dvd', 'Charge'), ('dvd', 'Planta'))), ('Impressos', (('vhs', 'Jornal'), ('dvd', 'Boletim'), ('dvd', 'Panfleto'), ('dvd', 'Propaganda'), ('dvd', 'Revista'), ('dvd', 'História em quadrinho'), ('dvd', 'Livro'), ('dvd', 'Folder'), ('dvd', 'Cardápio'), ('dvd', 'Poesia'))), ('Vídeos', (('fIL', 'Filme'), ('dvd', 'Documentário'), ('dvd', 'Propaganda'), ('dvd', 'Desenho')))], max_length=5, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_video', models.FileField(blank=True, null=True, upload_to='Video/', verbose_name='Video:')),
                ('vid_duracao', models.DurationField(blank=True, null=True, verbose_name='Duração:')),
                ('vid_arq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo')),
                ('vid_texto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Transcricao')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fot_imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='imagem_projeto_arq', verbose_name='Imagem:')),
                ('fot_arq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_documento', models.FileField(blank=True, null=True, upload_to='Documento/', verbose_name='Documento')),
                ('doc_numero_de_caixa', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Numero de caixa::')),
                ('doc_numero_de_paginas', models.DecimalField(blank=True, decimal_places=0, max_digits=3000, null=True, verbose_name='Numero de Paginas:')),
                ('doc_arq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo')),
                ('doc_texto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Transcricao')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aud_duracao', models.DurationField(blank=True, null=True, verbose_name='Duração:')),
                ('aud_audio', models.FileField(blank=True, null=True, upload_to='Audio/', verbose_name='Audio')),
                ('aud_arq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo')),
                ('aud_texto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Transcricao')),
            ],
        ),
    ]
