# Generated by Django 2.2.4 on 2020-09-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_auto_20200915_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='arq_palavras_chaves',
            field=models.CharField(max_length=225, null=True, verbose_name='Palavras chaves:'),
        ),
        migrations.DeleteModel(
            name='PalavrasChave',
        ),
    ]
