# Generated by Django 3.0.6 on 2020-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0008_auto_20200711_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arq_destinatario',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Destinatario:'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arq_emitente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Emitente:'),
        ),
    ]
