# Generated by Django 3.0.6 on 2020-07-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0009_auto_20200713_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='arq_numero_de_caixa',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Numero de caixa::'),
        ),
    ]
