# Generated by Django 3.0.6 on 2020-07-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_arquivo_arq_numero_de_caixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='doc_numero_de_caixa',
        ),
    ]
