# Generated by Django 2.2.4 on 2020-07-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0011_remove_documento_doc_numero_de_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arq_tipo_de_documento',
            field=models.CharField(choices=[('Documentos Pessoais', (('DPI', 'Identidade'), ('DPCN', 'Certidão de nascimento'), ('DPCB', 'Certidão de batismo'), ('DPCC', 'Certidão de casamento'), ('DPCO', 'Certidão de óbito'))), ('Pessoais', (('PC', 'Correspondência'), ('PD', 'Diário'), ('PA', 'Anotação'), ('PRC', 'Receita de comida'), ('PDM', 'Documento médico'))), ('Jurídicos', (('JP', 'Processo'), ('JT', 'Testamento'), ('JI', 'Inventário'), ('JD', 'Depoimento'), ('JDs', 'Despacho'), ('JS', 'Sentença'), ('JA', 'Acórdão'))), ('Governamentais', (('GR', 'Relatório'), ('GA', 'Ata'), ('GL', 'Lei'), ('GR', 'Resolução'), ('GD', 'Decreto'), ('GC', 'Constituição'), ('GLs', 'Listas'), ('GRI', 'Registro de imóvel'), ('GRA', 'Registro de cobrança'), ('GRT', 'Registro de trabalho'), ('GCA', 'Carta de alforria'), ('GRCV', 'Recibo de compra e venda'), ('GAp', 'Apólice'))), ('Relatos', (('RD', 'Depoimento'), ('RE', 'Entrevista'), ('RR', 'Relato'), ('RM', 'Música'))), ('Iconográficos', (('IF', 'Fotografia'), ('ID', 'Desenho'), ('IM', 'Mapa'), ('IP', 'Pintura'), ('IC', 'Charge'), ('IP', 'Planta'))), ('Impressos', (('IJ', 'Jornal'), ('IB', 'Boletim'), ('IPn', 'Panfleto'), ('IPr', 'Propaganda'), ('IR', 'Revista'), ('IHQ', 'História em quadrinho'), ('IL', 'Livro'), ('IFl', 'Folder'), ('ICr', 'Cardápio'), ('IPs', 'Poesia'))), ('Vídeos', (('VF', 'Filme'), ('VD', 'Documentário'), ('VP', 'Propaganda'), ('VDs', 'Desenho')))], max_length=20, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
