# Generated by Django 2.2.4 on 2020-07-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0013_auto_20200720_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='aud_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='doc_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='fot_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='palavraschave',
            name='pc_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
    ]
