# Generated by Django 2.2.4 on 2020-07-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0015_auto_20200721_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='aud_arq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
    ]
