# Generated by Django 2.2.4 on 2020-07-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0016_auto_20200721_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavraschave',
            name='pc_arq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
    ]
