# Generated by Django 2.2.4 on 2020-07-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0017_auto_20200721_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='aud_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='doc_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='fot_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='palavraschave',
            name='pc_arq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid_arq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
    ]
