# Generated by Django 2.2.4 on 2020-07-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0018_auto_20200721_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='arq_tipo_de_documento',
        ),
    ]
