# Generated by Django 2.2.4 on 2020-07-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0019_remove_arquivo_arq_tipo_de_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDeDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdd_geral', models.CharField(max_length=100, null=True, verbose_name='Tipo de Documento Geral:')),
                ('tdd_especifico', models.CharField(max_length=100, null=True, verbose_name='Tipo de Documento Especifico:')),
            ],
        ),
    ]
