# Generated by Django 2.2.4 on 2020-07-24 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0020_tiposdedocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='arq_tdd_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.TiposDeDocumento'),
        ),
    ]
