# Generated by Django 2.2.4 on 2020-07-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0021_arquivo_arq_tdd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='aud_audio',
            field=models.FileField(blank=True, null=True, upload_to='user_directory_path/', verbose_name='Audio'),
        ),
    ]
