# Generated by Django 2.2.4 on 2020-08-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0024_auto_20200729_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='arq_cargo_des',
            field=models.CharField(max_length=100, null=True, verbose_name='Cargo de Destinatario:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_cargo_emi',
            field=models.CharField(max_length=100, null=True, verbose_name='Cargo de Emitente:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_cdd',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Numero de CDD:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_custodia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Custodia:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_idioma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Idioma:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_local_emissao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Local Emissao:'),
        ),
    ]
