# Generated by Django 2.2.4 on 2020-08-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0025_auto_20200802_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdedocumento',
            name='tdd_especifico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Documento Especifico:'),
        ),
    ]
