# Generated by Django 2.2.4 on 2020-08-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0026_auto_20200802_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arq_usu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.UsuarioComum'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='pro_usuarios',
            field=models.ManyToManyField(through='projetos.ProjetosDosUsuarios', to='usuario.UsuarioComum'),
        ),
        migrations.AlterField(
            model_name='projetosdosusuarios',
            name='pdu_usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.UsuarioComum'),
        ),
    ]
