# Generated by Django 2.2.4 on 2020-08-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0027_auto_20200811_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='arq_usu_id',
        ),
    ]
