# Generated by Django 2.2.4 on 2020-08-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0028_remove_arquivo_arq_usu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='arq_desc',
        ),
    ]
