# Generated by Django 2.2.4 on 2020-08-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0029_remove_arquivo_arq_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='arq_numero_de_caixa',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_autenticacao',
            field=models.CharField(choices=[('O', 'Original'), ('C', 'Copia')], max_length=1, null=True, verbose_name='Autenticação:'),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='arq_localizacao_do_acervo',
            field=models.CharField(max_length=100, null=True, verbose_name='Localização do acervo:'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arq_cidade',
            field=models.CharField(max_length=20, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arq_estado',
            field=models.CharField(max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
