# Generated by Django 2.2.4 on 2020-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0030_auto_20200814_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='arq_tipo_de_formato',
            field=models.CharField(choices=[('Impresso', 'Impresso'), ('Manuscrito', 'Manuscrito'), ('Video', 'Video'), ('Audio', 'Audio'), ('Fotografia', 'Fotografia'), ('Mapa', 'Mapa'), ('Pintura', 'Pintura'), ('Gravura', 'Gravura'), ('Outros', 'Outros')], max_length=5, null=True, verbose_name='Tipo de Formato:'),
        ),
    ]
