# Generated by Django 2.2.4 on 2020-08-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0031_arquivo_arq_tipo_de_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='fot_tamanho',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamanho:'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arq_tipo_de_formato',
            field=models.CharField(max_length=10, null=True, verbose_name='Tipo de Formato:'),
        ),
    ]
