# Generated by Django 2.2.4 on 2020-08-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0034_auto_20200814_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioCultura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_oficio', models.TextField(max_length=100, null=True, verbose_name='Oficio:')),
                ('pc_expressao', models.TextField(max_length=100, null=True, verbose_name='Formas de expressão:')),
                ('pc_lugares', models.CharField(max_length=100, null=True, verbose_name='Lugares:')),
                ('pc_celebracoes', models.TextField(max_length=100, null=True, verbose_name='Celebrações')),
                ('pc_edificacoes', models.TextField(max_length=100, null=True, verbose_name='Edificações')),
                ('pc_arq', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo')),
            ],
        ),
    ]
