# Generated by Django 2.2.4 on 2020-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0035_patrimoniocultura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniocultura',
            name='pc_celebracoes',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Celebrações'),
        ),
        migrations.AlterField(
            model_name='patrimoniocultura',
            name='pc_edificacoes',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Edificações'),
        ),
        migrations.AlterField(
            model_name='patrimoniocultura',
            name='pc_expressao',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Formas de expressão:'),
        ),
        migrations.AlterField(
            model_name='patrimoniocultura',
            name='pc_lugares',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugares:'),
        ),
        migrations.AlterField(
            model_name='patrimoniocultura',
            name='pc_oficio',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Oficio:'),
        ),
    ]
