# Generated by Django 2.2.4 on 2020-08-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0038_auto_20200815_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniocultura',
            name='pc_arq',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Arquivo'),
        ),
    ]
