# Generated by Django 2.2.4 on 2020-08-15 16:42

from django.db import migrations, models
import projetos.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0040_auto_20200815_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='aud_audio',
            field=models.FileField(blank=True, null=True, upload_to=projetos.models.user_directory_path_audio_file, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='doc_documento',
            field=models.FileField(blank=True, null=True, upload_to=projetos.models.user_directory_path_documento_file, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='fot_imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='imagem_projeto_arq', verbose_name='Imagem:'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid_video',
            field=models.FileField(blank=True, null=True, upload_to=projetos.models.user_directory_path_video_file, verbose_name='Video:'),
        ),
    ]
