# Generated by Django 2.2.4 on 2020-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0041_auto_20200815_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arq_cargo_des',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo de Destinatario:'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arq_cargo_emi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo de Emitente:'),
        ),
    ]
