# Generated by Django 2.2.4 on 2020-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0042_auto_20200816_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arq_cidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='arq_estado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado'),
        ),
    ]
