
# Generated by Django 2.2.4 on 2020-09-09 16:02


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        ('usuario', '0002_auto_20200824_1649'),

        ('projetos', '0044_auto_20200816_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_arquivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Projetos')),
                ('noti_bolsista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolsista', to='usuario.UsuarioComum')),
                ('noti_pesquisador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisador', to='usuario.UsuarioComum')),

            ],
        ),
    ]
