# Generated by Django 2.2.4 on 2020-08-23 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('projetos', '0044_auto_20200816_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_nomeDoPesquisador', models.CharField(max_length=100)),
                ('noti_arquivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Projetos')),
                ('noti_bolsista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.UsuarioComum')),
            ],
        ),
    ]
