# Generated by Django 2.2.4 on 2020-08-24 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0045_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='noti_bolsista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolsista', to='usuario.UsuarioComum'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='noti_nomeDoPesquisador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisador', to='usuario.UsuarioComum'),
        ),
    ]
