# Generated by Django 2.2.4 on 2020-08-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0046_auto_20200823_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='noti_nomeDoPesquisador',
            new_name='noti_pesquisador',
        ),
    ]
